const router = require('express').Router();

router.use('/auth', require('./auth.routes'));
router.use('/students', require('./student.routes'));
router.use('/faculty', require('./faculty.routes'));
router.use('/subjects', require('./subject.routes'));
router.use('/marks', require('./marks.routes'));
router.use('/notes', require('./note.routes'));
router.use('/assignments', require('./assignment.routes'));
router.use('/exams', require('./exam.routes'));
router.use('/feedback', require('./feedback.routes'));
router.use('/badges', require('./badge.routes'));
router.use('/admin', require('./cleanup.routes'));
router.use('/admin/storage', require('./storage.routes'));
router.use('/admin/semesters', require('./semester.routes'));
router.use('/notifications', require('./notification.routes'));
router.use('/admin/bulk-students', require('./bulkStudent.routes'));
router.use('/dashboard', require('./dashboard.routes'));
router.use('/contact', require('./contact.routes'));
router.use('/lookup', require('./lookup.routes'));
router.use('/materials', require('./material.routes'));
router.use('/debug-pdf', require('./debugPdf.routes'));
module.exports = router;