module.exports = {
  NOTIFICATION_TYPES: [
    'IMPORTANT_ANNOUNCEMENT',
    'NEW_ACTIVITY',
    'ASSIGNMENT_CREATED',
    'ASSIGNMENT_DUE_SOON',
    'ASSIGNMENT_OVERDUE',
    'MARKS_PUBLISHED',
    'EXAM_SCHEDULED',
    'EXAM_APPROACHING',
    'TIMETABLE_UPDATED',
    'NEW_NOTES_PUBLISHED',
    'ACADEMIC_ALERT',
    'SYSTEM_ALERT',
  ],
  RECIPIENT_TYPES: ['ALL_STUDENTS', 'ALL_FACULTY', 'YEAR', 'SEMESTER', 'SECTION', 'BATCH', 'USER'],
};